name: Package WoW Addon

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug zip file name
        run: |
          echo "Expected zip: ChattyLittleNpc_Wrath_of_the_Lich_King_voiceovers-${{ github.ref_name }}.zip"
          ls -lh

      - name: Create Addon ZIP
        run: |
          zip -r "ChattyLittleNpc_Wrath_of_the_Lich_King_voiceovers-${{ github.ref_name }}.zip" ChattyLittleNpc_Wrath_of_the_Lich_King_voiceovers

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "ChattyLittleNpc_Wrath_of_the_Lich_King_voiceovers-${{ github.ref_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
